CLIP_PROMPTS = [
    "asphalt",
    "concrete",
    "brick",
    "cobblestone",
    "tile",
    "hardwood",
    "grass",
    "dirt",
    "gravel",
    "sand",
    "mulch",
    "leaves",
    "snow",
    "ice",
    "metal",
    "sidewalk",
    "plastic",
    "ceramic",
    "granite",
    "slate",
    "pavement",
    "crosswalk",
    "train track",
    "boardwalk",
    "astroturf",
    "wood chips",
    "paver stones",
    "carpet",
    "linoleum",
    "speckled",
    "striped",
    "wood",
    "mud",
]
PREFIX = "This image contains"

CLIP_PROMPTS = [f"{PREFIX} {prompt}" for prompt in CLIP_PROMPTS]
